### ISSUE TITLE
Background color when content exceeds image height

### ISSUE THREAD

**Issue by screab** [teandra/vocesipian#2]
When there is more than two paragraphs of text on a page, the div containing it expands to wrap it and the extra space is left with a white color.

**Comment by teandra** [comment]
nu stiu ce naiba am facut ca nu se sincronizeaza

```
  From: screab <notifications@github.com>
```

 To: teandra/vocesipian vocesipian@noreply.github.com 
 Sent: Tuesday, 1 September 2015, 18:38
 Subject: [vocesipian] Background color when content exceeds image height (#2)

When there is more than two paragraphs of text on a page, the div containing it expands to wrap it and the extra space is left with a white color.—
